enyo.depends(
	//"Categories.js",
	//"PrayersStore.js",
	//"GroupsController.js",
	"CategoryController.js",
	"PrayersController.js",
	"SelectedCategoryController.js",
	"EditCategoryController.js",
	"PrayerViewController.js"
);